### ISSUE TITLE
Constant-folding

### ISSUE THREAD

**Issue by pkofod** [koaning/koaning.github.io#1]
This is probably the easiest way to make you aware of the discussion over at reddit.com/r/Julia, so here goes:
https://www.reddit.com/r/Julia/comments/3j49hn/julia_against_numba_and_rcpp_whats_happening/

Feel free to close it when you've seen it :)

**Comment by koaning** [comment]
oh cool. people read my ramblings. thanks for the notice! meaningful discussion as well. 

questions; would you consider yourself to very familiar with the julia language?

**Comment by pkofod** [comment]
Somewhat familier. Do you have a question?

**Comment by koaning** [comment]
1. what did you think of the blog post. the reddit is giving me some points of improvement, like comparing while keeping the n constant. 
2. do you use julia often professionally?
